import type { Metadata } from "next";
import { Onest } from "next/font/google";
import "@/app/globals.css";
import Providers from "@/components/providers";
import Navbar from "@/components/sections/nav";

export const metadata: Metadata = {
  title: "London Web Design | Artistweb | Digital Agency",
  description: "Generated by create next app",
};

const onest = Onest({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${onest.className} antialiased overflow-x-hidden`}>
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
